name: Build-Scheduled
on:
  push:
    branches:
      - master
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  generate:
    name: Generate Feeds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: dotnet build
        run: dotnet build -c Debug
      - name: dotnet run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd src/WatchDotNetGitHubRepos
          TARGET_REPOS=(
            dotnet/announcements
            dotnet/runtime
            dotnet/runtimelab
            dotnet/sdk
            dotnet/csharplang
            dotnet/roslyn
            dotnet/aspnetcore
            dotnet/diagnostics
            dotnet/maui
            dotnet/efcore
            dotnet/installer
            dotnet/Comet
          )
          dotnet run -c Debug --no-build -- issues-and-pull-requests --output-dir ../../public/IssuesAndPRs ${TARGET_REPOS[*]}

          RELEASE_WATCH_REPOS=(
            ${TARGET_REPOS[*]}
            autofac/Autofac
            domaindrivendev/Swashbuckle.AspNetCore
            dotnet/command-line-api
            fluentassertions/fluentassertions
            grpc/grpc
            grpc/grpc-dotnet
            icsharpcode/ILSpy
            jbogard/MediatR
            microsoft/CsWin32
            microsoft/microsoft-ui-xaml
            microsoft/WindowsAppSDK
            mysql-net/MySqlConnector
            neuecc/MessagePack-CSharp
            npgsql/npgsql
            unoplatform/uno
            App-vNext/Polly
            AutoMapper/AutoMapper
            AvaloniaUI/Avalonia
            FluentValidation/FluentValidation
            JamesNK/Newtonsoft.Json
            JoshClose/CsvHelper
            StackExchange/StackExchange.Redis
            Tyrrrz/CliFx
          )
          dotnet run -c Debug --no-build -- releases --output-dir ../../public/Releases ${RELEASE_WATCH_REPOS[*]}
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
